version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: authservice-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: authservice
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

  mongo-express:
    image: mongo-express:latest
    container_name: authservice-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - auth-network

  
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: authservice-rabbitmq
    restart: always
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auth-network

volumes:
  mongodb_data:
  rabbitmq_data:  

networks:
  auth-network:
    driver: bridge